SELECT tblSPUDefault.SPUID,
tblSVLAttributesDefaultAfforestation.PreTypeID,
tblSVLAttributesDefaultAfforestation.SW_FoliageBiomassCarbon,
tblSVLAttributesDefaultAfforestation.SW_MerchantableBiomassCarbon,
tblSVLAttributesDefaultAfforestation.SW_OtherBiomassCarbon,
tblSVLAttributesDefaultAfforestation.SW_CoarseRootBiomassCarbon,
tblSVLAttributesDefaultAfforestation.SW_FineRootBiomassCarbon,
tblSVLAttributesDefaultAfforestation.HW_FoliageBiomassCarbon,
tblSVLAttributesDefaultAfforestation.HW_MerchantableBiomassCarbon,
tblSVLAttributesDefaultAfforestation.HW_OtherBiomassCarbon,
tblSVLAttributesDefaultAfforestation.HW_CoarseRootBiomassCarbon,
tblSVLAttributesDefaultAfforestation.HW_FineRootBiomassCarbon,
tblSVLAttributesDefaultAfforestation.VFSoilPoolC_AG,
tblSVLAttributesDefaultAfforestation.VFSoilPoolC_BG,
tblSVLAttributesDefaultAfforestation.FSoilPoolC_AG,
tblSVLAttributesDefaultAfforestation.FSoilPoolC_BG,
tblSVLAttributesDefaultAfforestation.MSoilPoolC,
tblSVLAttributesDefaultAfforestation.SSoilPoolC_AG,
tblSVLAttributesDefaultAfforestation.SSoilPoolC_BG,
tblSVLAttributesDefaultAfforestation.StemSnagPoolC_SW,
tblSVLAttributesDefaultAfforestation.BranchSnagPoolC_SW,
tblSVLAttributesDefaultAfforestation.StemSnagPoolC_HW,
tblSVLAttributesDefaultAfforestation.BranchSnagPoolC_HW
FROM tblSVLAttributesDefaultAfforestation INNER JOIN
tblSPUDefault ON (
	tblSVLAttributesDefaultAfforestation.EcoBoundaryID =
		tblSPUDefault.EcoBoundaryID
	) AND (
		tblSVLAttributesDefaultAfforestation.AdminBoundaryID =
			tblSPUDefault.AdminBoundaryID)
GROUP BY tblSPUDefault.SPUID,
tblSVLAttributesDefaultAfforestation.PreTypeID,
tblSVLAttributesDefaultAfforestation.SW_FoliageBiomassCarbon,
tblSVLAttributesDefaultAfforestation.SW_MerchantableBiomassCarbon,
tblSVLAttributesDefaultAfforestation.SW_OtherBiomassCarbon,
tblSVLAttributesDefaultAfforestation.SW_CoarseRootBiomassCarbon,
tblSVLAttributesDefaultAfforestation.SW_FineRootBiomassCarbon,
tblSVLAttributesDefaultAfforestation.HW_FoliageBiomassCarbon,
tblSVLAttributesDefaultAfforestation.HW_MerchantableBiomassCarbon,
tblSVLAttributesDefaultAfforestation.HW_OtherBiomassCarbon,
tblSVLAttributesDefaultAfforestation.HW_CoarseRootBiomassCarbon,
tblSVLAttributesDefaultAfforestation.HW_FineRootBiomassCarbon,
tblSVLAttributesDefaultAfforestation.VFSoilPoolC_AG,
tblSVLAttributesDefaultAfforestation.VFSoilPoolC_BG,
tblSVLAttributesDefaultAfforestation.FSoilPoolC_AG,
tblSVLAttributesDefaultAfforestation.FSoilPoolC_BG,
tblSVLAttributesDefaultAfforestation.MSoilPoolC,
tblSVLAttributesDefaultAfforestation.SSoilPoolC_AG,
tblSVLAttributesDefaultAfforestation.SSoilPoolC_BG,
tblSVLAttributesDefaultAfforestation.StemSnagPoolC_SW,
tblSVLAttributesDefaultAfforestation.BranchSnagPoolC_SW,
tblSVLAttributesDefaultAfforestation.StemSnagPoolC_HW,
tblSVLAttributesDefaultAfforestation.BranchSnagPoolC_HW

