SELECT tblDMAssociationDefault.DefaultDisturbanceTypeID
FROM tblDisturbanceTypeDefault INNER JOIN tblDMAssociationDefault ON 
tblDisturbanceTypeDefault.DistTypeID = tblDMAssociationDefault.DefaultDisturbanceTypeID
WHERE tblDMAssociationDefault.AnnualOrder > 1
GROUP BY tblDMAssociationDefault.DefaultDisturbanceTypeID
ORDER BY tblDMAssociationDefault.DefaultDisturbanceTypeID;
