select composite_flux_indicator.id, composite_flux_indicator_category_tr.category_name, composite_flux_indicator_category_tr.subcategory_name, composite_flux_indicator_tr.name, flux_indicator.id, flux_indicator.name
from composite_flux_indicator_category_tr
inner join composite_flux_indicator on composite_flux_indicator.composite_flux_indicator_category_id = composite_flux_indicator_category_tr.composite_flux_indicator_category_id
inner join composite_flux_indicator_tr on composite_flux_indicator_tr.composite_flux_indicator_id = composite_flux_indicator.id
inner join composite_flux_indicator_value on composite_flux_indicator_value.composite_flux_indicator_id = composite_flux_indicator.id
inner join flux_indicator on flux_indicator.id = composite_flux_indicator_value.flux_indicator_id
where composite_flux_indicator_category_tr.locale_id = 1 and composite_flux_indicator_tr.locale_id = 1